### ISSUE TITLE
Seriously not a function?

### ISSUE THREAD

**Issue by hackmyscience** [brianchirls/Seriously.js#100]
Working through your seriously.js tutorial and receiving the following error in the chrome browser: Seriously is not a function. I've set up a repo "VR" for experimenting with your code. Clearly am missing something very basic, but complete novice here.

**Comment by brianchirls** [comment]
Yup, you misspelled the `src` attribute on your first script tag as `scr`. And on your image tag. Also, you're gonna need to move your last script tag below the image and canvas tags so they exist by the time that script runs.

There's more, but I'm gonna let you figure it out on your own. Good luck.
