### ISSUE TITLE
SeriouslyJs.org Website Down

### ISSUE THREAD

**Issue by zschuessler** [brianchirls/Seriously.js#129]
http://seriouslyjs.org , which displayed a neat example of this code on top of OK GO's video, seems inaccessible.

Google has deindexed the domain, and the internet archive posts the last known archive as June 13th, 2016.

**Comment by brianchirls** [comment]
Thanks for the heads-up. Should be back up now. Can you confirm?

**Comment by zschuessler** [comment]
Looks good!

**Comment by aendra-rininsland** [comment]
Site's down again, looks like the domain expired and somebody snapped it up. 

Suggestion: set up seriously.js.org — for instructions on getting a .js.org subdomain, visit [here](https://js.org/).
