### ISSUE TITLE
Enable floating point textures

### ISSUE THREAD

**Issue by positlabs** [brianchirls/Seriously.js#132]
I realize that this isn't widely supported, but it would be nice to have access to floating point textures if they are available.

We could add a flag to the Seriously options. It would check for support, then use the OES_texture_float extension if it's available.

@brianchirls What do you think? Feasible?

https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float

**Comment by brianchirls** [comment]
I started playing with this a long time ago but I gave up. Feel free to give it a shot. Start here:
https://github.com/brianchirls/Seriously.js/blob/develop/seriously.js#L782

**Comment by positlabs** [comment]
Rad! I will play around with it. I only need it to work on Chrome desktop, so I'm hopeful.

I know it's basically unsupported on mobile, but I'm curious... what issues did you run into?

**Comment by positlabs** [comment]
I enabled it but didn't see any difference in quality in my app. Oh well

**Comment by brianchirls** [comment]
D'oh!

I'm sure there are all kinds of subtleties here. I suspect floating point textures are probably only useful if you're going to do some other kind of processing with them. Like something with depth maybe?

**Comment by positlabs** [comment]
I was hoping it would give me more subtlety in the colors, but I think it's simply a limitation of my webcam.

On another note, I used the kaleidoscope node today. Super fun!

![lpl-mercury_2016-10-07_13-19-53](https://cloud.githubusercontent.com/assets/1918844/19205245/13e6a136-8c96-11e6-85dd-8c6907a091aa.jpeg)
![lpl-mercury_2016-10-07_13-12-47](https://cloud.githubusercontent.com/assets/1918844/19205244/13e66bee-8c96-11e6-8538-2d2102549d0f.jpeg)
![lpl-mercury_2016-10-07_13-11-26](https://cloud.githubusercontent.com/assets/1918844/19205246/13e6d282-8c96-11e6-8faf-9a9bf3efc826.jpeg)
