### ISSUE TITLE
Question: Resize Target when browser window changes while maintaining transform cover?

### ISSUE THREAD

**Issue by justono1** [brianchirls/Seriously.js#133]
I have the reformat set on load with the cover mode. I have an event listener set up for the window resize but I can't seem to find a function in the seriously js that will resize the canvas as the window size changes.

**Comment by justono1** [comment]
Sorry for the premature comment I ended up figuring it out.

In my resize event listener I first had to set the new target size then just recall the reformat width and height. I was skipping the step of applying the new size to the target.

**Comment by brianchirls** [comment]
Glad you figured it out.
