### ISSUE TITLE
seriously.three.js - access __webglframebuffer post r71 threejs

### ISSUE THREAD

**Issue by damskii** [brianchirls/Seriously.js#148]
seriously.three.js breaks from r71 three.js - access to the __webglFramebuffer was changed in the THREE.WebGLRenderTarget to I think - THREE.WebGLProperties file.

Below might be the new way to access props with the target, about a far as i got though...

r71
frameBuffer = target.__webglFramebuffer;

r71+
var props = renderer.properties.get(target);

**Comment by damskii** [comment]
var targetProperties = renderer.properties.get(target);
var webglFramebuffer = targetProperties.__webglFramebuffer;

Confirmed the above code works to get webglFramebuffer from THREE.WebGLProperties for seriously & threejs r71+

**Comment by eulphean** [comment]
@damskii Thanks for this note. 
I'm at this point. How do you convert the webglFramebuffer into a gl texture that seriously is expecting?
