### ISSUE TITLE
Save to file

### ISSUE THREAD

**Issue by curlyfro** [brianchirls/Seriously.js#75]
i'm running nodejs.  how can i save the rendered effect to a file?

**Comment by gabrielstuff** [comment]
Not very clear what you are trying to achieve. Do you want seriously to run with node ? or do you want to save an image from a seriously filter ?

**Comment by brianchirls** [comment]
See #79

**Comment by cara** [comment]
Has anybody tried to use slimerjs for rendering a video and has it worked?

**Comment by positlabs** [comment]
I think a coworker of mine has done it before. 

Another option would be to use Electron + MediaRecorder API

https://developers.google.com/web/updates/2016/01/mediarecorder
https://electron.atom.io/
