### ISSUE TITLE
Broken module wrapper in Chrome app

### ISSUE THREAD

**Issue by positlabs** [brianchirls/Seriously.js#85]
For some reason, this module wrapper doesn't work in my chrome app. I was using AMD and switched to CommonJS, and then I saw the issue.
```
(function (root, factory) {
	'use strict';
        ...
}(this, function (window) {
```
The code above causes the window object to be undefined. Change `this` to `window` and it works fine.

**Comment by brianchirls** [comment]
Can you elaborate? What are you using to require? browserify? Do you have any example code?

I assume this is for all the plugins as well, right?

**Comment by positlabs** [comment]
Yep, using browserify. I haven't dug into it too much, but I think it is caused by browserify wrapping all of the modules in an immediate function, which causes `this` to reference the function, and not the window.

```javascript
this === window; // true

// enter browserify's wrapper
(function(){
  this === window; // false
})()
```

**Comment by juancabrera** [comment]
thank you @positlabs !

**Comment by brianchirls** [comment]
Okay, @positlabs and @juancabrera. Here you go. If you run into any more problems with this one, feel free to re-open this issue.

**Comment by positlabs** [comment]
Nice, thanks!
