### ISSUE TITLE
Blend RGB Colors Using Gamma 1.0

### ISSUE THREAD

**Issue by brianchirls** [brianchirls/Seriously.js#86]
Typical blending by weighted average of input colors stinks, as explained here:
https://www.youtube.com/watch?v=LKnqECcg6Gw

We should enable gamma-corrected blending for at least the following effects:
- blend
- layers
- blur
- directionalblur
- accumulator
- split

I'm undecided whether to enable this by default. It probably has a much better effect, and many users will probably not know to enable it. On the other hand, it's not backward compatible. But we don't exactly follow strict semver here. Any thoughts?

**Comment by forresto** [comment]
I'd say go for it, and make the old way an option default: false.

**Comment by brianchirls** [comment]
I'd like to make this setting mimic how Photoshop does it. I can't quite figure out the math. I found this formula (pseudo-code), which makes sense:

```
tmp = pow(source1, GAMMA) * alpha + pow(source2, GAMMA) * (1.0 - alpha);
output = pow(tmp, 1.0/GAMMA);
```
But Photoshop's default value is `1.00`, which has the same effect of setting `GAMMA = 2.0`. Does anybody know what Photoshop does with that parameter value?

Here's what it says in the CS6 manual:
> **Blend RGB Colors Using Gamma** Controls how RGB colors blend together to produce composite data (for example, when you blend or paint layers using Normal mode). When the option is selected, RGB colors are blended in the color space corresponding to the specified gamma. A gamma of 1.00 is considered “colorimetrically correct” and should result in the fewest edge artifacts. When the option is deselected, RGB colors are blended directly in the document’s color space.

Then there is the question of what the default value should be (or if it should be adjustable at all). The video implies that gamma should be `2.0`, but according to [Wikipedia](http://en.wikipedia.org/wiki/Gamma_correction#Windows.2C_Mac.2C_sRGB_and_TV.2Fvideo_standard_gammas), it should be in the `2.2` range.

**Comment by brianchirls** [comment]
The After Effects manual on [color management](https://helpx.adobe.com/after-effects/using/color-management.html#linearize_working_space_and_enable_linear_blending) and [color basics](https://helpx.adobe.com/after-effects/using/color-basics.html#gamma_and_tone_response) is a little more helpful.

Also, I wonder if banding will be an issue. May have to run some experiments.

**Comment by brianchirls** [comment]
This is now applied to the develop branch if anyone wants to give it a try. I decided to go with a straight `blendGamma` parameter as the exponent and not try to mimic whatever weirdness Photoshop is doing.

Temporarily hold off on applying this to `layers` since it would require a major refactor and might hurt performance. What do you guys think? It's also worth considering later on for `repeat` as well.

**Comment by positlabs** [comment]
Ohhhh this could be really good for Chromavore. I'll give it a spin when I get some time.

**Comment by brianchirls** [comment]
Yeah, @positlabs, would appreciate your feedback.

**Comment by brianchirls** [comment]
You too @forresto.

BTW, for the record, the way to turn this off is to just set `blendGamma` to 1.0

**Comment by positlabs** [comment]
I ran chromavore for 5 seconds an compared the results. Here they are.

old gamma
![nogamma1](https://cloud.githubusercontent.com/assets/1918844/8149950/12ff540a-128c-11e5-8ad4-d3acddf591a3.png)

new gamma
![gamma1](https://cloud.githubusercontent.com/assets/1918844/8149951/13005e36-128c-11e5-9190-b41ad21f3bfa.png)

It's generally brighter, but details seem more pronounced with gamma 1.0.

**Comment by brianchirls** [comment]
Either way, it looks gorgeous. Good work, @positlabs. I think it's an artistic choice at that point, no? Better to have the option than not at all, right?

Do you like it?

**Comment by positlabs** [comment]
Thanks!

I do like it! I agree that it should be optional, but I'll be using it from now on.

**Comment by brianchirls** [comment]
Awesome. Just to clarify the terminology and controls...

This does not work the same way as Photoshop. It uses the formula [above](https://github.com/brianchirls/Seriously.js/issues/86#issuecomment-85330961), so if you set `blendGamma` to 1.0, it reverts back to the old way. The default is 2.2.

I'm gonna leave this open a little longer and think about what to do about the `layers` effect. I'm open to any further suggestions/feedback.

**Comment by brianchirls** [comment]
I'm gonna close this one for now. Will re-consider what to do about layers and repeat later.
