### ISSUE TITLE
using a canvas as source does not work with animation

### ISSUE THREAD

**Issue by bitterulf** [brianchirls/Seriously.js#89]
I try to add a Seriously effect on a canvas displays a animation (p5.js).
seriously.go() works fine with a video but with canvas as input source it only renders once.

How can i force Seriously to redraw after the input canvas has changed?

**Comment by brianchirls** [comment]
After you're done updating the canvas, call `.update()` on the Source node that references it.

**Comment by bitterulf** [comment]
Thank you very much allways tried to call the update on the end node.
Works like a charm!

**Comment by brianchirls** [comment]
Great! Would love to see what you're working on.

**Comment by bitterulf** [comment]
At the moment i try to combine several browser based libraries into a toolbelt to create interactive storytelling.
And Seriously.js looks really nice to create effects on top of other technologies like p5.js and 3d engines.
http://stuff.spielstand.net/effect/

**Comment by alvarobyrne** [comment]
If i may say, imho, this info should be somewhere in the main documentation, or examples or wiki. thank you.
