### ISSUE TITLE
Chroma key not working on Safari 8.0.6

### ISSUE THREAD

**Issue by juancabrera** [brianchirls/Seriously.js#95]
The text "Let's make magic." is behind the canvas running a chroma key video.

This is Chrome.
![screen shot 2015-06-16 at 4 19 18 pm](https://cloud.githubusercontent.com/assets/355253/8193547/9bb76130-1443-11e5-8001-7bcd34cf1134.png)

This is Safari.
![screen shot 2015-06-16 at 4 21 52 pm](https://cloud.githubusercontent.com/assets/355253/8193582/d5f28564-1443-11e5-84b4-6001ed75232f.png)

It works on older versions of Safari tho.

**Comment by brianchirls** [comment]
Thanks for filing. It'll be easier to debug if you could post a working sample.

Have you tried it with the latest "develop" branch? I wonder if this might be the same as #88.

**Comment by juancabrera** [comment]
Already the code is deep into a react/isomorphic/webpack stack, will try to extract it soon.

Gonna

**Comment by juancabrera** [comment]
Hey, tried with the version of the develop branch and worked!

Thank you!

**Comment by brianchirls** [comment]
Glad it worked out. I'll try to get this to release ASAP.
