### ISSUE TITLE
Accumulator bug on Lollipop

### ISSUE THREAD

**Issue by positlabs** [brianchirls/Seriously.js#98]
Accumulator is bugging out on Lollipop's system web view (basically equivalent to chrome). It doesn't seem to agree with the frame buffer swapping, for some reason. 

https://drive.google.com/file/d/0BxHpmZYCB3c2bU1vX3JhaTZ6ZDQ/view?usp=sharing

**Comment by brianchirls** [comment]
What kind of device are you using? I just tried this on my Nexus 4 running Android 5.1.1, and it works just fine. Tried emulating a Nexus 5, but can't get WebGL to work on the emulator.

**Comment by positlabs** [comment]
I'm on Android 5.1.1, too. Nexus 6.

It totally works in chrome, but not the system web view. I thought the two were functionally equivalent, but maybe not.

I'll try building with [Crosswalk](https://crosswalk-project.org/) when I have time. Hopefully that will solve the issue.

**Comment by positlabs** [comment]
Crosswalk did the trick. Sad that system webview doesn't, but I suppose I can close this issue.
